name: 'Scan Files in a Folder'
description: 'Scan all files and output them as a .json file.'
inputs:
  folder:  
    description: 'Folder to scan'
    required: true
    default: './'
  email:  
    description: 'Action email'
    required: false
    default: 'actions@github.com'
  username:  
    description: 'Action username'
    required: false
    default: 'GitHub Actions'    
runs:
  using: 'node16'
  main: 'index.js'
